QA_interface_app/urls.py
from django.conf.urls import url
from QA_interface_app import views

# template urls

app_name= 'QA_interface_app'

urlpatterns= [
    url(r'^$', views.report ,name = 'reports'),
    url(r'^register$', views.register ,name = 'register'),
    url(r'^qa_machine_api$', views.qa_machine_API.as_view()),
    url(r'^api/$', views.CreateView.as_view(), name="CreateView"),
    url(r'^user_login$', views.user_login ,name = 'user_login'),
    url(r'^logout/', views.user_logout, name= 'logout'),
    url(r'^readme/', views.readme, name= 'readme'),
    ]

QA_monitoring/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from QA_interface_app import views



urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^logout/', views.user_logout, name= 'logout'),
    url(r'^QA_machines_app/', include('QA_interface_app.urls')),
    url(r'^qa_machine_api$', views.qa_machine_API.as_view()), # must  be shifted  later in QA_interface_app
    url(r'^register/$', views.register ,name = 'register'),
    url(r'^special/', views.special, name='special'),
]

QA_interface_app/models.py
from django.contrib.auth.models import User
from django.db import models

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)
    # addditionals
    codewars_username= models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics', blank=True)
    def __str__(self):
        return self.user.name



class  QA_machine_DB(models.Model):
    QAmachine = models.CharField( max_length = 64, unique=True)
    status = models.CharField(max_length=32,null=True, blank=True)
    owner= models.CharField(max_length=32,null=True, blank=True)
    comments= models.CharField(max_length=32,null=True, blank=True)
    def __str__(self):
        return "%s" %  (self.id)

class Report(models.Model):
    # primary key set automatically from Django
    store = models.CharField(max_length= 128,null=True, blank=True)
    service = models.CharField(max_length= 128,null=True, blank=True)
    user = models.CharField(max_length= 64,null=True, blank=True)
    deployement_date = models.CharField(max_length= 128,null=True, blank=True)
    dump_date = models.CharField(max_length= 128,null=True, blank=True)
    branch= models.CharField(max_length= 128, null=True, blank=True)
    #FK_report=models.ForeignKey(QA_machine_DB, on_delete=models.CASCADE)
    FK_report=models.ForeignKey(QA_machine_DB, null=True, blank=True, on_delete=models.SET_NULL)
    #  publications = models.ManyToManyField(Publication)
    def __str__(self):
        return "%s %s" % (self.store, self.user)



## how to reset migrations
## if problem with migrations
#https://stackoverflow.com/questions/34720511/unable-to-make-migrations-after-changes-in-table-in-django-1-8

QA_interface_app/forms.py
from django import forms
from django.views.generic.edit import UpdateView
from QA_interface_app.models import Report, QA_machine_DB, UserProfileInfo
from django.contrib.auth.models import User
from django.forms import ModelForm


class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=['username', 'email', 'password']

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model= UserProfileInfo
        fields= ['codewars_username','profile_pic']


class FormReport ( forms.Form):
    store = forms.CharField()
    service = forms.CharField()
    user = forms.CharField()
    deployement_date = forms.CharField()
    dump_date = forms.CharField()
    branch= forms.CharField(widget= forms.Textarea)

class QAmachine (forms.Form):
    QAmachine= forms.CharField()
    QAmachine_status=forms.CharField()
    store = forms.CharField()
    service = forms.CharField()
    user = forms.CharField()
    deployement_date = forms.CharField()
    dump_date = forms.CharField()
    branch= forms.CharField()

class BookingForm(forms.ModelForm):
    make_list_of_tuple = lambda list_machine  :  [tuple( [i,i]) for i in list_machine]
    MACHINES= tuple( QA_machine_DB.objects.values_list('QAmachine',flat=True))
    CHOICE_QA_MACHINES= make_list_of_tuple(MACHINES)
    QAmachine= forms.ModelChoiceField(queryset= QA_machine_DB.objects.values_list('QAmachine',flat=True), empty_label="QA machines")

    class Meta():
        model= QA_machine_DB
        fields= ['QAmachine', 'owner', 'comments','status']
        # http://nanvel.name/2014/03/django-change-modelform-widget
        widgets = {
                   'owner':forms.TextInput(attrs={'placeholder':'owner'}),
                   'comments':forms.TextInput(attrs={'placeholder':'comments'}),
                   'status': forms.RadioSelect( choices=[('busy','busy'),('free','free')])}

QA_interface_app/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render
from QA_interface_app.models import Report, QA_machine_DB, UserProfileInfo
from QA_interface_app import forms
from QA_interface_app.forms import BookingForm,UserForm,UserProfileInfoForm
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import qa_machine_serializer
from rest_framework import generics
# for login / logout / register
from django.contrib.auth import authenticate , login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required


class qa_machine_API(APIView):
    "  acces to the API with the following command :     "
    def get(self, request):
        queryset = QA_machine_DB.objects.order_by('QAmachine')
        serialized = qa_machine_serializer(queryset, many=True)
        return Response(serialized.data)

    def put(self,request,pk):
        queryset = QA_machine_DB.objects.get(pk=id)
        #request.method == 'PUT':
        serializer = qa_machine_serializer(queryset, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


def index( request):
    return render( request,'QA_interface_app/index.html')

def readme( request):
    return render( request,'QA_interface_app/documentation.html')


def register(request):
    registered=False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form= UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user= user_form.save()
            user.set_password(user.password)
            user.save()

            profile= profile_form.save(commit=False)
            profile.user= user

            if 'profile_pic' in request.FILES:
                profile.profile_pic= request.FILES['profile_pic']
            profile.save()

            registered= True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form= UserForm()
        profile_form= UserProfileInfoForm()

    return render(request, 'QA_interface_app/registration.html',{'user_form': user_form,
                        'profile_form': user_form,
                        'registered': registered,})


def user_login (request):
    if  request.method == 'POST':
        username= request.POST.get('username')
        password= request.POST.get('password')

        user = authenticate( username= username , password= password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

        else:
            print('someone tried to login and failed!')
            print("Username: {} and password {}" .format(username, password))
            return HttpResponse ( "invalid login details supplied")
    else:
        return render(request, 'QA_interface_app/login.html', {})


@login_required
def  user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def special(request):
    return HttpResponse('you are logged in , nice! ')


@login_required
def report( request):

    #  information in about the machine in the database
    ############################################################
    report_list= Report.objects.order_by('service')#[:5] # to limit the list
    report_dict={'report': report_list}
    qa_machine_list= QA_machine_DB.objects.order_by('QAmachine')
    qa_machine_dict= {'qa_report': qa_machine_list }


    #   information   in  the  Form to transport to the database
    ##############################################################
    # all of this until the next # line is a work around
    Booking= BookingForm(request.POST)

    if request.method == 'POST':
    # TODO change this workaround
    #   WORK AROUND we do here what the form should do .....
        post_request_dict = (dict(request.POST)) # convert queryset
        information_from_form=QA_machine_DB.objects.get(QAmachine=post_request_dict['QAmachine'][0])
        information_from_form.status= post_request_dict['status'][0]
        information_from_form.owner= post_request_dict['owner'][0]
        information_from_form.comments= post_request_dict['comments'][0]
        information_from_form.save()
    #######################
        if Booking.is_valid(): # by update is the form not valid . It does not matter  we just want to post the information .....
            return  render(request, 'QA_interface_app/monitoring.html', context= {'reports':report_list , 'machines': qa_machine_list,'BookingForm':Booking })

        else:
            #print('Form not valid', Booking.errors)
            return render(request, 'QA_interface_app/monitoring.html', context= {'reports':report_list , 'machines': qa_machine_list,'BookingForm':Booking })

    return render(request, 'QA_interface_app/monitoring.html', context= {'reports':report_list , 'machines': qa_machine_list,'BookingForm':Booking })

templates/QA_interface_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title> QA Machine overview </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment-with-locales.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/locale/en-gb.js"></script>

    </script>

  </head>
  <body>
  <nav clase= 'navbar navbar-default navbar-static-top'>
    <div class="container">
      <ul class= 'nav navbar-vav'>
        <li><a class="navbar-brand" href="{% url 'index' %}"> Home </a></li>
        <li><a class="navbar-brand" href="{% url 'QA_interface_app:reports' %}">Overview  QA machines</a></li>
        <li><a class="navbar-brand" href="{% url 'QA_interface_app:readme' %}" > Readme</a></li>
        <li><a class="navbar-brand" href="{% url 'QA_interface_app:register' %}">Register</a></li>
        {% if user.is_authenticated %}
        <li><a class= 'navbar-brand'  href="{% url 'QA_interface_app:logout' %}">logout</a>   </li>
        {% else %}
        <li> <a class= 'navbar-link' href="{% url 'QA_interface_app:user_login' %}">login</a>   </li>
        {% endif %}

      </ul>
    </div>
  </nav>
  <div class="container">
    {% block body_block %}

    {% endblock %}
  </div>

  </body>
</html>

templates/QA_interface_app/documentation.html
{% extends 'QA_interface_app/base.html' %}

{% block body_block %}
{% load staticfiles %}

<html >
<head>
<meta charset="utf-8">
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment-with-locales.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/locale/de.js"></script>
</head>
<body>

<h2> About 'free' and 'busy' status </h2>
<p> how to find if a  QA machine is busy? :  First we collect in the machine QA machine information in the  rev.txt or release.yml file about the branches deployed.</p>
<p>Then based on this data and  the diagram below we find out if the status of the  QA machine is busy or free. </p>
<img src= 'https://gitlab.com/remitoudic/QA_monitoring_2/raw/master/static/images/QA_machine_project_%20logic_busy.jpg' >

    <!--<img src=  "{% static "/images/QA_machine_project_ logic_busy.jpg"   %}">   -->

<p> Example : </p>
Let say  we collected  2 branche names in the machine QA007 :
<ul>
<li>'master'</li>
<li>'story/BOSS-77777-fiege-20-quentin-order-export'  (   In jira in QA in Progress  there is a ticket with name 'BOSS-QA007')</li>
</ul>
then the machine is consider  'busy' and will be in  orange displayed.

<h2> About the blue and orange buttons </h2>
Orange is for busy Qa machine  and blue for free.  By cliking on it,  the content and the history of rev.txt / release.yml will be
displayed below.


<h2> About login and registration </h2>
To be able to see any content , you must be login.
Please  log with:
<ol>
  <li>username: contorion</li>
  <li>password: contorion</li>
</ol>

<h2> About this project:  </h2>
This project  use a django server.The backend is entirely written in python.
<p>  For more detail contact remi,toudic@contorion.de  :)  </p>

<h2> About the installation </h2>
<p> In a QA machine </p>
<ul>
  <li> clone the project to a qa machine</li>
  <li> check that  python3 and pip are installed </li>
  <ul>
    cammand: python3 -V
    command :  pip3 --version
  </ul>
  <li> run script install_environment.py</li>
  <ul>
    <li>command python  install_environment.py</li>
  </ul>
  <li> run </li>

</ul>
{% endblock %}
</html>

templates/QA_interface_app/form_page.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title> form Page </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styling.css' %}" />
  </head>
  <body>
    <h1> Form  for QA_machine  </h1>
    <div class="container">
        <div class="jumbotron">

        <h1> ###################### </h1>
        <form method="post">
            {{Booking.as_p}}
            {% csrf_token %}
          <input type="submit" class=" btn btn primary" value="book">
        </form>

        </div>
    </div>
  </body>
</html>

templates/QA_interface_app/index.html
{% extends 'QA_interface_app/base.html' %}


{% block body_block %}

      <div class="jumbotron">
        <h1> QA monitoring Project </h1>

        {% if user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'QA_interface_app:reports' %}" role="button">QA Machines overview </a>
        <br>
        {%else%}
         <h3> Please loggin for contents </h3>
         {% endif %}
         <br>
         {% if user.is_staff  %}
         <button type="button" class="btn btn-default">start  Data import process manually</button>
         {% endif %}
    </div>
{% endblock %}

templates/QA_interface_app/login.html
{% extends "QA_interface_app/base.html" %}
{% block body_block %}

<div class="jumbotron">

  {% if user.is_authenticated %}
  <h1> Cool you are logged in  :) </h1>
 {%else%}
  <h1> Please login</h1>
  <form class="" action="{% url 'QA_interface_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username"></label>
    <input type="text" name="username" placeholder="Username">
    <label for="password">Password</label>
    <input type="password" name="password">
    <input type="submit" name="" value="login">
  </form>
{% endif %}
</div>
</div>
{% endblock %}

templates/QA_interface_app/monitoring.html
{% extends 'QA_interface_app/base.html' %}


{% block body_block %}
<body>
  <div class="container">
    <div class="jumbotron">
      <h2>Looking for a QA machine to deploy ?  </h2>
      Below are displayed the QA machine names with their availability. <br />

      For more information about the content below , please have look at the readme . <br />

    </div>

    <div class="jumbotron">
With the submit button, you can change the status of a machine, leave a comment or give a owner to the machine.  <br />
<p> </p>
    <form   class="form-group" method="post" novalidate >
        {% csrf_token %}
         <table  >
           <td>
              {{ BookingForm.QAmachine}}
            </td>
             <td>
               {{ BookingForm.owner.errors }}
               {{ BookingForm.owner}}
             </td>
             <td>
               {{ BookingForm.comments.errors }}
               {{ BookingForm.comments}}
             </td>
             <td>
               {% for radio in BookingForm.status %}
               {{ radio }}
               {% endfor %}
             </td>
        </table>
      <input type="submit" class="btn btn-success" value="submit status change" style="float: right;"   >
</div>
 </form >

      {% if machines %}
     <div class="panel-group" id="accordion">

      <div class="panel panel-default">
        {% for machine in machines %}
            <div class="panel-heading">
              <h4 class="panel-title">

        <a  class="btn btn-info" data-toggle="collapse" data-parent="#accordion" href="#table{{machine.id}}" onclick="this.style.color = 'black'"> <b> Machine: </b>  {{machine.QAmachine}} => {{machine.status}} </a>
        <button type="button" class="btn btn-secondary"> <b>owner:</b>  {{machine.owner}}</button>
        <button type="button" class="btn btn-secondary"> <b> comments: </b> {{machine.comments}}</button>
         </h4>
            </div>
            <div id="table{{machine.id}}" class="panel-collapse collapse">
              <div class="panel-body">
                {% if reports %}
                <table class="table table-striped">
                  <thead>
                    <tr>
                      <th style="width:5%"> store </th>
                      <th style="width:10%"> Service </th>
                      <th style="width:10%"> Branch </th>
                      <th style="width:10%"> User </th>
                      <th style="width:10%"> Deployement date </th>
                      <th style="width:10%"> Dump Age </th>
                    </tr>
                  </thead>
                  {% for QA in reports %}
                  {% if machine.id == QA.FK_report_id %}
                  <tr>
                    <td>{{QA.store}}</td>
                    <td>{{QA.service}}</td>
                    <td>{{QA.branch}}</td>
                    <td>{{QA.user}}</td>
                    <td>{{QA.deployement_date}}</td>
                    <td id='dump_Age'>{{QA.dump_date}}</td>
                  </tr>
                  {% endif %}
                  {%endfor%}
                </table>
              </div>
                </div>
              {% endif %}
                {%endfor%}
              {% endif %}
      </div>

  </div>

  </div>




</body>



<script >

var Buttons_list= document.getElementsByClassName("btn btn-info")
var Button=''
for(i=0; i<Buttons_list.length ; i++)  { Button += Buttons_list[i].text;
                                           if (Buttons_list[i].text.includes("busy") == true)
                                                 {
                                                 Buttons_list[i].style.background = "#ff9966"}
                                          else { Buttons_list[i].style.background =   "#20c3ff"   }}

function time_diff(date) {
  var now = moment(new Date()).lang("en"); //todays date
  var start = moment(date, "DD/MM/YY - HH:mm"); // another date
  var duration = moment.duration(now.diff(start));
  var days = duration.humanize();
  if (days == "Invalid date") {
    days = "-";
}
  return days;}

dates_dump = document.querySelectorAll("#dump_Age")
for(i=0; i<dates_dump.length ; i++)  {dates_dump[i].innerText=time_diff(dates_dump[i].innerText) };
</script>

{% endblock %}
</html>

templates/QA_interface_app/registration.html
{% extends 'QA_interface_app/base.html' %}
{% load staticfiles %}

{% block body_block %}
<div class="container">
<div class="jumbotron">
  {% if registered %}
  <h1> Thank you for registering</h1>
  {%else%}
  <h1> Register here ! </h1>
  <h3> Fill out the form</h3>
   <form  enctype="multipart/form-data", method="post">
     {% csrf_token%}
     {{user_form.as_p}}
     {{UserProfileInfoForm.as_p}}
     <input type="submit" name="" value="Register">

   </form>
   {% endif %}

 </div>

</div>

{% endblock %}